name:                safety-envelopes-sentinels
version:             0.1.1.0
github:              "helq/safety-envelopes-sentinels"
license:             BSD3
author:              "Elkin Cruz"
copyright:           "2020 Elkin Cruz"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/helq/safety-envelopes-sentinels#readme>

dependencies:
- base >= 4.7 && < 5
- pipes

library:
  source-dirs: src
  ghc-options:
  - -fwarn-incomplete-patterns
  - -fno-warn-overlapping-patterns
  dependencies:
  # Taken from Agda.cabal : https://github.com/agda/agda/blob/40e78a74f7fef6a63af8c967fe228cc791b3ec62/Agda.cabal
  - ieee754 >= 0.7.8 && < 0.9
  - text >= 1.2.3.1 && < 1.3

executables:
  sentinels-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - safety-envelopes-sentinels

tests:
  sentinels-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - safety-envelopes-sentinels
